### PR TITLE
Updated indexer.md with new Java code samples, updated examples/indexer/java code samples, atomic transfer graphic fix

### LINKED ISSUE #426: Incorrect Atomic Transfers Graphic
### Arrow is facing the wrong way. Graphic found: https://developer.algorand.org/docs/build-apps/apps/
Github: https://github.com/algorand/docs/blob/941c5ed2653ccae054153581db8242ee5d84d34b/docs/imgs/app-3.jpg
CleanShot_2021-06-14_at_19 34 592x

### PR DESCRIPTION
**Pull request by iskysun96**
### The Java codes for indexer were outdated due to syntax changes.
- updated the code snippets on the indexer.md file
- updated all the code samples under features/examples/indexer/java.
- Fixes #426

### CODE REVIEW

File: examples/indexer/java/AccountInfo.java [hunk 1]
```diff
@@ -3,25 +3,33 @@
...
+
 import org.json.JSONObject;
 
 public class AccountInfo {
     public Client indexerInstance = null;
     // utility function to connect to a node
     private Client connectToNetwork(){
         final String INDEXER_API_ADDR = "localhost";
-        final int INDEXER_API_PORT = 8980;       
+        final int INDEXER_API_PORT = 8981;
```
Comment (ryanRfox) [inline examples/indexer/java/AccountInfo.java:18]: Please revert to 8980 in all instances on this page. This is our standard port assignment for indexer.

File: examples/indexer/java/LookupApplication.java [hunk 2]
```diff
@@ -6,43 +6,150 @@
...
-//       "global-state": [],
-//       "creator": "GHFRLVOMKJNTJ4HY3P74ZR4CNE2PB7CYAUAJ6HVAVVDX7ZKEMLJX6AAF4M",
-//       "local-state-schema": {
-//         "num-uint": 0,
-//         "num-byte-slice": 0
-//       },
-//       "global-state-schema": {
-//         "num-uint": 0,
-//         "num-byte-slice": 0
+// response should look similar to this...
```
Comment (ryanRfox) [inline examples/indexer/java/LookupApplication.java:36]: This response is surely better than what we had. However, it is a bit lengthy and without context. Please consider using the "Hello World" application, as it will be much more concise and you may reference the this page for additional context for the keys and programs:
https://developer.algorand.org/docs/features/asc1/stateful/sdks/

File: examples/indexer/java/SearchTransactionsNote.java [hunk 3]
```diff
@@ -1,27 +1,44 @@
...
-        SearchTransactionsNote ex = new SearchTransactionsNote();
-        IndexerClient indexerClientInstance = (IndexerClient) ex.connectToNetwork();
-        byte[] notePrefix = "showing prefix".getBytes();
-        String response = indexerClientInstance.searchForTransactions().notePrefix(notePrefix).execute().toString();
-        JSONObject jsonObj = new JSONObject(response.toString());
-        System.out.println("Transaction Info: " + jsonObj.toString(2)); // pretty print json
+        IndexerClient indexerClientInstance = connectToNetwork();
+        Response<TransactionsResponse> resp = indexerClientInstance.searchForTransactions()
+                .notePrefix("showing prefix".getBytes())
+                .minRound(10894697L)
```
Comment (ryanRfox) [inline examples/indexer/java/SearchTransactionsNote.java:27]: Is the "L" going to cause problems in this field? It seems misplaced to me. Also in the next line and a couple other places.

**Review by ryanRfox — CHANGES_REQUESTED** [review]
I like the error handling. Just a couple of changes needed.

File: examples/indexer/java/SearchTransactionsNote.java (hunk 3 above)
Comment (iskysun96) [reply examples/indexer/java/SearchTransactionsNote.java:27]: @rfustino Could you double check this criteria?

File: examples/indexer/java/AccountInfo.java (hunk 1 above)
Comment (rfustino) [reply examples/indexer/java/AccountInfo.java:18]: yes.. change to 8980

File: examples/indexer/java/LookupApplication.java (hunk 2 above)
Comment (rfustino) [reply examples/indexer/java/LookupApplication.java:36]: as for the long response, ya, sometimes after a few repeating groups in the response, i just chop it off and put a "..." after it, also feel free to add this link in the comment. for more info on applications, see. this link https://developer.algorand.org/docs/features/asc1/stateful/sdks/

**Review by rfustino — COMMENTED** [review]
It will not cause problems and works as is. Sometimes a L is needed if too long.

**Comment by iskysun96** [comment]
@ryanRfox Requested Fix editted and pushed!

**Comment by iskysun96** [comment]
Atomic Transfer graphic at https://developer.algorand.org/docs/build-apps/apps/ was incorrect.
Updated the graphic.

**Review by ryanRfox — APPROVED** [review]
